{% set name = "legend-pygeom-l1000" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_l1000-{{ version }}.tar.gz
  sha256: 7b4575c2d33775a07b520542c4f089ed368296b64b37a3d347c075f0dfa7e7ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - legend-pygeom-l1000 = l1000geom.cli:dump_gdml_cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - legend-pygeom-hpges
    - legend-pygeom-optics >=0.13
    - legend-pygeom-tools >=0.0.18
    - numpy
    - pint
    - pyg4ometry
    - dbetto
    - pylegendmeta >=v0.9.0
    - pyyaml
    - scipy
    - git

test:
  imports:
    - l1000geom
  commands:
    - pip check
    - legend-pygeom-l1000 dummy.gdml
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Geometry model of the LEGEND-1000 experimental setup
  home: https://github.com/legend-exp/legend-pygeom-l1000
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-l1000.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-l1000

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
