{% set name = "legend-pygeom-l1000" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_l1000-{{ version }}.tar.gz
  sha256: b5fac159de54185b0952d3b98d62623fecc1b9afbb09c2434a3e447dde9e0343

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - legend-pygeom-l1000 = pygeoml1000.cli:dump_gdml_cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - legend-pygeom-hpges >=0.9.0
    - legend-pygeom-optics >=0.15
    - legend-pygeom-tools >=0.0.25
    - numpy
    - pint
    - pyg4ometry
    - dbetto
    - pylegendmeta >=1.3.1
    - pyyaml
    - scipy
    - git

test:
  imports:
    - l1000geom
    - pygeoml1000
  commands:
    - pip check
    - legend-pygeom-l1000 dummy.gdml
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Geometry model of the LEGEND-1000 experimental setup
  home: https://github.com/legend-exp/legend-pygeom-l1000
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-l1000.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-l1000

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
