schema_version: 1

context:
  name: legend-pygeom-l1000
  version: 0.6.0
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/legend_pygeom_l1000-${{ version }}.tar.gz
  sha256: 8d815ff557f41d3e6b2ba07fe102cce0dd32294d3180a367d05cf60ee3c2c291

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - legend-pygeom-l1000 = pygeoml1000.cli:dump_gdml_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=7
    - pip
  run:
    - python >=${{ python_min }}
    - legend-pygeom-hpges >=0.9.0
    - legend-pygeom-optics >=0.15
    - legend-pygeom-tools >=0.6.0
    - numpy
    - pint
    - pyg4ometry
    - dbetto
    - pylegendmeta >=1.9.0
    - pyyaml
    - scipy
    - jsonschema
    - gitpython
tests:
  - python:
      imports:
        - l1000geom
        - pygeoml1000
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - git
    script:
      - git clone https://github.com/legend-exp/legend1000-metadata.git
      - LEGEND1000_METADATA=./legend1000-metadata legend-pygeom-l1000 dummy.gdml

about:
  summary: Geometry model of the LEGEND-1000 experimental setup
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/legend-exp/legend-pygeom-l1000
  repository: https://github.com/legend-exp/legend-pygeom-l1000
  documentation: https://legend-pygeom-l1000.readthedocs.io

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
